version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LinkManager.Web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LinkManager.Tests"
    schedule:
      interval: "weekly"
